### ISSUE TITLE
mer_annotate.py: ./get_entities.sh: line 95: /usr/bin/awk: Argument list too long

### ISSUE THREAD

**Issue by alexeyev** [lasigeBioTM/MultiNEL-corpus#1]
Dear colleagues, thank you for your work!

I've been following your instructions in `README.md` and I've encountered the 'awk error' when running 

    python3 mer_annotate.py es

Error text:
` ./get_entities.sh: line 95: /usr/bin/awk: Argument list too long`

It seems that the problem is somewhere in `merpy`. Do you know any simple workarounds to hot-fix this? Thank you.

UPD: Running on WSL with GNU awk installed.

**Comment by fjmc** [comment]
Hi,
MER was developed to work with one sentence at each time. 
Are you using long texts?
cheers

**Comment by alexeyev** [comment]
Hi, thanks. I was simply running the instructions in README, i.e. I wasn't even using my own data.

**Comment by fjmc** [comment]
did you install gawk?
https://merpy.readthedocs.io/en/latest/getting_started.html#awk

**Comment by alexeyev** [comment]
> did you install gawk? https://merpy.readthedocs.io/en/latest/getting_started.html#awk

Yes. Checked again just in case:
`gawk is already the newest version (1:4.1.4+dfsg-1build1).`

**Comment by pedroruas18** [comment]
Hi 

Thank you for your interest!

I've checked and it seems that it is a problem exclusively related with long ICD10 code names. merpy uses awk to match code names with the text, but there are codes that are too long, so awk raises the error 'Argument list too long'. According to this [post](https://serverfault.com/questions/163371/linux-command-line-character-limit) there is an hard-coded limit for the length that an argument can have in linux shell. [

As a workaround, I've updated the code in order to truncate code names longer than 65 characters, and after running the code again the error seems to have disappeared. I've also added some features to the code, like a progress bar during annotation and a sentence segmentation step before annotation, and have improved the code documentation for clarity.

Feel free to reach to us if you face more problems

**Comment by alexeyev** [comment]
Hi!

> As a workaround, I've updated the code in order to truncate code names longer than 65 characters, and after running the code again the error seems to have disappeared. 

No errors now. Thank you.

> I've also added some features to the code, like a progress bar during annotation

Very helpful indeed!

Again, thank you for your quick response and -- have a great day.
